/**
 * Type definitions for chat function
 */

/**
 * Base request interface with action discriminator
 */
export interface BaseChatRequest {
  action: 'init' | 'summary' | 'message' | 'history'
}

/**
 * Initialize chat session request
 */
export interface InitChatRequest extends BaseChatRequest {
  action: 'init'
  githubUrl: string
  ref?: string
  force?: boolean  // Force reprocess repository
}

/**
 * Generate summary request
 */
export interface SummaryRequest extends BaseChatRequest {
  action: 'summary'
  sessionId: string
  regenerate?: boolean  // Force regenerate summary even if cached
}

/**
 * Send chat message request
 */
export interface MessageRequest extends BaseChatRequest {
  action: 'message'
  sessionId: string
  message: string
  ragConfig?: RAGConfig
}

/**
 * Get chat history request
 */
export interface HistoryRequest extends BaseChatRequest {
  action: 'history'
  sessionId: string
  limit?: number
  offset?: number
}

/**
 * Union type for all chat requests
 */
export type ChatRequest = InitChatRequest | SummaryRequest | MessageRequest | HistoryRequest

/**
 * RAG configuration options
 */
export interface RAGConfig {
  matchThreshold?: number      // Similarity threshold (0-1), default: 0.7
  matchCount?: number           // Number of chunks to retrieve, default: 5
  includeSummary?: boolean      // Include summary in context, default: true
}

/**
 * Repository summary structure (generated by LLM)
 */
export interface RepositorySummary {
  title: string
  description: string
  keyFeatures: string[]
  techStack: string[]
  primaryLanguage: string
  documentationLinks: DocumentationLink[]
  quickStart: string
  useCases: string[]
  additionalInfo?: string
}

/**
 * Documentation link in summary
 */
export interface DocumentationLink {
  title: string
  url: string
}

/**
 * RAG source citation
 */
export interface RAGSource {
  chunkId: string
  chunkText: string
  documentUrl: string
  similarity: number
}

/**
 * Chat message stored in database
 */
export interface ChatMessage {
  id: string
  sessionId: string
  role: 'user' | 'assistant' | 'system'
  content: string
  sources?: RAGSource[]
  metadata?: Record<string, unknown>
  createdAt: string
}

/**
 * Chat session info
 */
export interface ChatSessionInfo {
  sessionId: string
  repositoryId: string
  repositoryOwner: string
  repositoryName: string
  repositoryRef: string
  sessionCreatedAt: string
  messageCount: number
  hasSummary: boolean
}

/**
 * Response for init action
 */
export interface InitChatResponse {
  success: boolean
  sessionId: string
  repositoryId: string
  status: 'created' | 'existing'
  message: string
}

/**
 * Response for summary action
 */
export interface SummaryResponse {
  success: boolean
  summary: RepositorySummary
  fromCache: boolean
  modelUsed: string
}

/**
 * Response for message action
 */
export interface MessageResponse {
  success: boolean
  messageId: string
  answer: string
  sources: RAGSource[]
  usedRagContext: boolean
  usedFallback: boolean  // True if no relevant docs found but LLM provided general answer
  modelUsed: string
}

/**
 * Response for history action
 */
export interface HistoryResponse {
  success: boolean
  sessionInfo: ChatSessionInfo
  messages: ChatMessage[]
  summary?: RepositorySummary
  totalMessages: number
}

/**
 * Error response
 */
export interface ErrorResponse {
  success: false
  error: string
  message: string
  details?: unknown
}

/**
 * Database record types
 */
export interface ChatSessionRecord {
  id: string
  repository_id: string
  created_at: string
  updated_at: string
  metadata: Record<string, unknown>
}

export interface ChatMessageRecord {
  id: string
  session_id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  sources: RAGSource[] | null
  metadata: Record<string, unknown>
  created_at: string
}

export interface RepositorySummaryRecord {
  id: string
  repository_id: string
  summary_json: RepositorySummary
  model_used: string
  generation_params: Record<string, unknown>
  created_at: string
  updated_at: string
}

/**
 * Repository info from data-aggregate
 */
export interface RepositoryInfo {
  id: string
  owner: string
  repo: string
  ref: string
  url: string
}

/**
 * Match documents result from RAG search
 */
export interface MatchDocumentsResult {
  chunk_id: string
  chunk_text: string
  document_url: string
  similarity: number
  repository_owner: string
  repository_name: string
  repository_ref: string
}

/**
 * OpenAI chat message format
 */
export interface OpenAIChatMessage {
  role: 'system' | 'user' | 'assistant'
  content: string
}

/**
 * OpenAI chat completion response
 */
export interface OpenAIChatResponse {
  id: string
  object: string
  created: number
  model: string
  choices: Array<{
    index: number
    message: {
      role: string
      content: string
    }
    finish_reason: string
  }>
  usage: {
    prompt_tokens: number
    completion_tokens: number
    total_tokens: number
  }
}
